import { TrademarkRecord } from './types.ts';

/**
 * Basis Data Pembanding Merek Terdaftar PDKI DJKI Indonesia
 * Memuat sampel representatif pendaftaran merek aktif di Direktorat Jenderal Kekayaan Intelektual (DJKI)
 * yang mencakup berbagai kelas Nice dan rumusan spesifikasi barang/jasa resmi.
 */
export const PDKI_DATABASE: TrademarkRecord[] = [
  {
    nomorPendaftaran: 'IDM000582914',
    nomorPermohonan: 'DID2016012891',
    namaMerek: 'FOREVER 21',
    pemilik: 'FOREVER 21, INC. (California, USA)',
    tanggalPenerimaan: '15 Maret 2016',
    tanggalPerlindungan: '15 Maret 2026',
    kelasNice: [25],
    uraianBarangJasa: 'Pakaian, termasuk kaos, kemeja, celana, gaun, rok, jaket; alas kaki seperti sepatu santai dan sandal; tutup kepala, yaitu topi bisbol dan baret.',
    statusPendaftaran: 'Terdaftar',
  },
  {
    nomorPendaftaran: 'IDM000789123',
    nomorPermohonan: 'DID2019054321',
    namaMerek: 'FOREVER',
    pemilik: 'PT CIPTA SANDANG ABADI (Jakarta, Indonesia)',
    tanggalPenerimaan: '10 Agustus 2019',
    tanggalPerlindungan: '10 Agustus 2029',
    kelasNice: [25],
    uraianBarangJasa: 'Pakaian jadi, pakaian rajut, kaos oblong, celana jeans, pakaian olahraga, kaus kaki; pakaian dalam.',
    statusPendaftaran: 'Terdaftar',
  },
  {
    nomorPendaftaran: 'IDM000921402',
    nomorPermohonan: 'DID2021034981',
    namaMerek: '4EVER BEAUTY',
    pemilik: 'PT PESONA KOSMETIKA INDONESIA (Surabaya, Indonesia)',
    tanggalPenerimaan: '22 Mei 2021',
    tanggalPerlindungan: '22 Mei 2031',
    kelasNice: [3],
    uraianBarangJasa: 'Sediaan-sediaan pembersih kosmetik, sabun mandi, losion wajah, krim pelembap, minyak wangi, riasan mata dan bibir.',
    statusPendaftaran: 'Terdaftar',
  },
  {
    nomorPendaftaran: 'IDM000452109',
    nomorPermohonan: 'DID2014029111',
    namaMerek: 'COOL & FRESH',
    pemilik: 'PT UNILEVER INDONESIA TBK (Tangerang, Indonesia)',
    tanggalPenerimaan: '04 Juni 2014',
    tanggalPerlindungan: '04 Juni 2024',
    kelasNice: [3],
    uraianBarangJasa: 'Sediaan untuk memutihkan dan mencuci; sediaan untuk membersihkan, mengilapkan; sabun; wangi-wangian; minyak atsiri; kosmetik; losion rambut; sediaan pembersih gigi.',
    statusPendaftaran: 'Perpanjangan Terdaftar',
  },
  {
    nomorPendaftaran: 'IDM000631890',
    nomorPermohonan: 'DID2017041908',
    namaMerek: 'SUPER COOL',
    pemilik: 'PT SARI MINUMAN SEGAR (Bekasi, Indonesia)',
    tanggalPenerimaan: '18 September 2017',
    tanggalPerlindungan: '18 September 2027',
    kelasNice: [32],
    uraianBarangJasa: 'Bir; air mineral dan air berkarbonasi serta minuman non-alkohol lainnya; minuman sari buah; sirop dan sediaan lain untuk membuat minuman, yaitu minuman isotonik dan sari buah apel.',
    statusPendaftaran: 'Terdaftar',
  },
  {
    nomorPendaftaran: 'IDM000889215',
    nomorPermohonan: 'DID2020087123',
    namaMerek: 'KOOL',
    pemilik: 'BRITISH AMERICAN TOBACCO (INVESTMENTS) LIMITED (London, UK)',
    tanggalPenerimaan: '14 November 2020',
    tanggalPerlindungan: '14 November 2030',
    kelasNice: [34],
    uraianBarangJasa: 'Tembakau yang diolah atau tidak diolah; produk tembakau; rokok elektrik dan sediaan cairan perasa rokok elektrik.',
    statusPendaftaran: 'Terdaftar',
  },
  {
    nomorPendaftaran: 'IDM000104859',
    nomorPermohonan: 'DID2006008129',
    namaMerek: 'AQUA',
    pemilik: 'PT TIRTA INVESTAMA (Jakarta Selatan, Indonesia)',
    tanggalPenerimaan: '20 Juli 2006',
    tanggalPerlindungan: '20 Juli 2026',
    kelasNice: [32],
    uraianBarangJasa: 'Air minum dalam kemasan, air mineral, air sumber pegunungan, air demineralisasi, air beroksigen, minuman penyegar berkarbonasi.',
    statusPendaftaran: 'Perpanjangan Terdaftar',
  },
  {
    nomorPendaftaran: 'IDM000512894',
    nomorPermohonan: 'DID2015031940',
    namaMerek: 'AKUA FRESH',
    pemilik: 'CV SUMBER AIR SENTOSA (Bogor, Indonesia)',
    tanggalPenerimaan: '11 Oktober 2015',
    tanggalPerlindungan: '11 Oktober 2025',
    kelasNice: [32],
    uraianBarangJasa: 'Air minum suling, air mineral tanpa rasa, sari buah jeruk dalam kemasan botol.',
    statusPendaftaran: 'Terdaftar',
  },
  {
    nomorPendaftaran: 'IDM000318942',
    nomorPermohonan: 'DID2011021940',
    namaMerek: 'BINTANG',
    pemilik: 'PT MULTI BINTANG INDONESIA TBK (Jakarta, Indonesia)',
    tanggalPenerimaan: '08 Maret 2011',
    tanggalPerlindungan: '08 Maret 2031',
    kelasNice: [32],
    uraianBarangJasa: 'Bir, bir hitam, bir bebas alkohol, shandy, minuman malt berkarbonasi.',
    statusPendaftaran: 'Perpanjangan Terdaftar',
  },
  {
    nomorPendaftaran: 'IDM000742119',
    nomorPermohonan: 'DID2019018420',
    namaMerek: 'STAR',
    pemilik: 'STAR BEVERAGES INTERNATIONAL LTD. (Singapura)',
    tanggalPenerimaan: '19 April 2019',
    tanggalPerlindungan: '19 April 2029',
    kelasNice: [32],
    uraianBarangJasa: 'Minuman energi, minuman berkarbonasi non-alkohol, sari buah konsentrat, air soda.',
    statusPendaftaran: 'Terdaftar',
  },
  {
    nomorPendaftaran: 'IDM000698124',
    nomorPermohonan: 'DID2018029145',
    namaMerek: 'STARLIGHT',
    pemilik: 'PT CAHAYA BINTANG TIMUR (Semarang, Indonesia)',
    tanggalPenerimaan: '02 Februari 2018',
    tanggalPerlindungan: '02 Februari 2028',
    kelasNice: [11],
    uraianBarangJasa: 'Lampu penerangan, bohlam LED, fitting lampu, lentera sorot elektrik, perlengkapan tata cahaya dekoratif.',
    statusPendaftaran: 'Terdaftar',
  },
  {
    nomorPendaftaran: 'IDM000490182',
    nomorPermohonan: 'DID2015011928',
    namaMerek: 'RATU KENCANA',
    pemilik: 'PT MUSTIKA RATU TBK (Jakarta, Indonesia)',
    tanggalPenerimaan: '17 Mei 2015',
    tanggalPerlindungan: '17 Mei 2025',
    kelasNice: [3],
    uraianBarangJasa: 'Kosmetik tradisional, lulur, masker wajah, minyak zaitun untuk kulit, sabun herbal alami, sampo.',
    statusPendaftaran: 'Terdaftar',
  },
  {
    nomorPendaftaran: 'IDM000812903',
    nomorPermohonan: 'DID2020041289',
    namaMerek: 'GOLDEN QUEEN',
    pemilik: 'QUEEN COSMETICS CORP. (Seoul, Korea Selatan)',
    tanggalPenerimaan: '09 Juli 2020',
    tanggalPerlindungan: '09 Juli 2030',
    kelasNice: [3],
    uraianBarangJasa: 'Krim anti-penuaan, serum wajah emas, kosmetik bibir, pembersih riasan wajah, alas bedak.',
    statusPendaftaran: 'Terdaftar',
  },
  {
    nomorPendaftaran: 'IDM000720419',
    nomorPermohonan: 'DID2018063219',
    namaMerek: 'EASY CLEAN',
    pemilik: 'PT WINGS SURYA (Surabaya, Indonesia)',
    tanggalPenerimaan: '05 September 2018',
    tanggalPerlindungan: '05 September 2028',
    kelasNice: [3],
    uraianBarangJasa: 'Deterjen cuci pakaian bubuk dan cair, sabun cuci piring, pembersih lantai, cairan pembersih kaca.',
    statusPendaftaran: 'Terdaftar',
  },
  {
    nomorPendaftaran: 'IDM000841920',
    nomorPermohonan: 'DID2020078129',
    namaMerek: 'EZ CLEAN',
    pemilik: 'PT MITRA SARANA BERSIH (Bandung, Indonesia)',
    tanggalPenerimaan: '12 November 2020',
    tanggalPerlindungan: '12 November 2030',
    kelasNice: [3],
    uraianBarangJasa: 'Sediaan pembersih rumah tangga, cairan penghilang kerak porselen, sabun pembersih serbaguna.',
    statusPendaftaran: 'Terdaftar',
  },
  {
    nomorPendaftaran: 'IDM000628190',
    nomorPermohonan: 'DID2017039201',
    namaMerek: 'KAPAL API',
    pemilik: 'PT SANTOS JAYA ABADI (Sidoarjo, Indonesia)',
    tanggalPenerimaan: '14 Agustus 2017',
    tanggalPerlindungan: '14 Agustus 2027',
    kelasNice: [30],
    uraianBarangJasa: 'Kopi, biji kopi sangrai, kopi bubuk, campuran kopi instan dengan gula dan krimer, ekstrak kopi.',
    statusPendaftaran: 'Terdaftar',
  },
  {
    nomorPendaftaran: 'IDM000773910',
    nomorPermohonan: 'DID2019047201',
    namaMerek: 'FIRE SHIP',
    pemilik: 'GLOBAL BEVERAGE VENTURES PTE. LTD. (Singapura)',
    tanggalPenerimaan: '29 Oktober 2019',
    tanggalPerlindungan: '29 Oktober 2029',
    kelasNice: [30],
    uraianBarangJasa: 'Kopi sangrai, minuman kopi kemasan siap minum, teh seduh, sediaan minuman cokelat bubuk.',
    statusPendaftaran: 'Terdaftar',
  },
  {
    nomorPendaftaran: 'IDM000539102',
    nomorPermohonan: 'DID2015059124',
    namaMerek: 'APPLE',
    pemilik: 'APPLE INC. (California, USA)',
    tanggalPenerimaan: '03 Maret 2015',
    tanggalPerlindungan: '03 Maret 2025',
    kelasNice: [9],
    uraianBarangJasa: 'Komputer, komputer tablet, telepon pintar, pemutar audio portabel, jam tangan pintar, sistem operasi komputer dan perangkat lunak aplikasi.',
    statusPendaftaran: 'Terdaftar',
  },
  {
    nomorPendaftaran: 'IDM000612940',
    nomorPermohonan: 'DID2017019842',
    namaMerek: 'APEL GADGET',
    pemilik: 'PT TEKNOLOGI NUSANTARA ELEKTRONIK (Jakarta Barat, Indonesia)',
    tanggalPenerimaan: '19 April 2017',
    tanggalPerlindungan: '19 April 2027',
    kelasNice: [9],
    uraianBarangJasa: 'Aksesori telepon seluler, pelindung layar kaca, kabel pengisi daya, pengisi daya nirkabel, penyuara telinga kabel dan nirkabel.',
    statusPendaftaran: 'Terdaftar',
  },
  {
    nomorPendaftaran: 'IDM000782190',
    nomorPermohonan: 'DID2019039102',
    namaMerek: 'INDOMIE',
    pemilik: 'PT INDOFOOD CBP SUKSES MAKMUR TBK (Jakarta Utara, Indonesia)',
    tanggalPenerimaan: '12 Juni 2019',
    tanggalPerlindungan: '12 Juni 2029',
    kelasNice: [30],
    uraianBarangJasa: 'Mi instan, bihun instan, bumbu mi instan, pasta, makaroni, sediaan yang terbuat dari tepung terigu.',
    statusPendaftaran: 'Terdaftar',
  },
  {
    nomorPendaftaran: 'IDM000910283',
    nomorPermohonan: 'DID2021019284',
    namaMerek: 'INDO NOODLE',
    pemilik: 'PT PANGAN JAYA MAKMUR (Tangerang, Indonesia)',
    tanggalPenerimaan: '02 Maret 2021',
    tanggalPerlindungan: '02 Maret 2031',
    kelasNice: [30],
    uraianBarangJasa: 'Mi kering, mi telur, kulit pangsit, suun, mi basah siap olah.',
    statusPendaftaran: 'Terdaftar',
  },
  {
    nomorPendaftaran: 'IDM000650192',
    nomorPermohonan: 'DID2017058190',
    namaMerek: 'GARUDA',
    pemilik: 'PT GARUDAFOOD PUTRA PUTRI JAYA TBK (Jakarta Barat, Indonesia)',
    tanggalPenerimaan: '07 Juli 2017',
    tanggalPerlindungan: '07 Juli 2027',
    kelasNice: [29, 30],
    uraianBarangJasa: 'Kacang olahan, kacang atom, kacang kulit asin, keripik kentang; biskuit, wafer, kembang gula, makanan ringan ekstrusi.',
    statusPendaftaran: 'Terdaftar',
  },
  {
    nomorPendaftaran: 'IDM000832190',
    nomorPermohonan: 'DID2020061920',
    namaMerek: 'EAGLE SNACK',
    pemilik: 'PT MAKANAN RINGAN NUSANTARA (Surabaya, Indonesia)',
    tanggalPenerimaan: '18 Agustus 2020',
    tanggalPerlindungan: '18 Agustus 2030',
    kelasNice: [29, 30],
    uraianBarangJasa: 'Kacang panggang berlapis tepung, keripik singkong gurih, kerupuk bawang, biskuit renyah.',
    statusPendaftaran: 'Terdaftar',
  },
  {
    nomorPendaftaran: 'IDM000491823',
    nomorPermohonan: 'DID2014041920',
    namaMerek: 'NIKE',
    pemilik: 'NIKE INNOVATE C.V. (Oregon, USA)',
    tanggalPenerimaan: '24 Agustus 2014',
    tanggalPerlindungan: '24 Agustus 2024',
    kelasNice: [25, 18],
    uraianBarangJasa: 'Pakaian olahraga, jaket latihan, celana pendek, kaos jersey, kaus kaki olahraga; alas kaki, khususnya sepatu lari, sepatu sepak bola, sepatu basket; tas punggung, tas ransel olahraga, tas gym.',
    statusPendaftaran: 'Perpanjangan Terdaftar',
  },
  {
    nomorPendaftaran: 'IDM000940182',
    nomorPermohonan: 'DID2021051928',
    namaMerek: 'NAIK SPORT',
    pemilik: 'CV MANDIRI KREASI BUSANA (Bandung, Indonesia)',
    tanggalPenerimaan: '14 September 2021',
    tanggalPerlindungan: '14 September 2031',
    kelasNice: [25],
    uraianBarangJasa: 'Pakaian pria dan wanita, pakaian senam, jaket bertudung, celana training, topi olahraga.',
    statusPendaftaran: 'Terdaftar',
  },
  {
    nomorPendaftaran: 'IDM000572189',
    nomorPermohonan: 'DID2016021948',
    namaMerek: 'SUNLIGHT',
    pemilik: 'UNILEVER N.V. (Rotterdam, Belanda)',
    tanggalPenerimaan: '09 November 2016',
    tanggalPerlindungan: '09 November 2026',
    kelasNice: [3],
    uraianBarangJasa: 'Sediaan pembersih piring dan peralatan dapur, cairan pencuci piring jeruk nipis, sabun cuci tangan antibakteri.',
    statusPendaftaran: 'Terdaftar',
  },
  {
    nomorPendaftaran: 'IDM000781290',
    nomorPermohonan: 'DID2019029184',
    namaMerek: 'MATAHARI BERSIH',
    pemilik: 'PT CAHAYA SURYA CHEMICAL (Semarang, Indonesia)',
    tanggalPenerimaan: '15 Maret 2019',
    tanggalPerlindungan: '15 Maret 2029',
    kelasNice: [3],
    uraianBarangJasa: 'Cairan pencuci piring konsentrat, sabun pembersih lemak dapur, deterjen pencuci serbaguna.',
    statusPendaftaran: 'Terdaftar',
  },
  {
    nomorPendaftaran: 'IDM000690214',
    nomorPermohonan: 'DID2018012891',
    namaMerek: 'ROYAL',
    pemilik: 'ROYAL BRANDS HOLDINGS B.V. (Amsterdam, Belanda)',
    tanggalPenerimaan: '05 Januari 2018',
    tanggalPerlindungan: '05 Januari 2028',
    kelasNice: [30],
    uraianBarangJasa: 'Cokelat batangan, permen cokelat praline, wafer lapis cokelat, bubuk kakao murni, biskuit mentega.',
    statusPendaftaran: 'Terdaftar',
  },
  {
    nomorPendaftaran: 'IDM000859102',
    nomorPermohonan: 'DID2020091823',
    namaMerek: 'KERAJAAN COKLAT',
    pemilik: 'PT KELUARGA MANIS NUSANTARA (Yogyakarta, Indonesia)',
    tanggalPenerimaan: '08 Oktober 2020',
    tanggalPerlindungan: '08 Oktober 2030',
    kelasNice: [30],
    uraianBarangJasa: 'Cokelat olahan, selai cokelat oles roti, cokelat compound, penganan manis berbahan dasar kakao.',
    statusPendaftaran: 'Terdaftar',
  },
  {
    nomorPendaftaran: 'IDM000810294',
    nomorPermohonan: 'DID2020038192',
    namaMerek: 'TOLAK ANGIN',
    pemilik: 'PT INDUSTRI JAMU DAN FARMASI SIDO MUNCUL TBK (Semarang, Indonesia)',
    tanggalPenerimaan: '25 Mei 2020',
    tanggalPerlindungan: '25 Mei 2030',
    kelasNice: [5],
    uraianBarangJasa: 'Obat herbal terstandar, jamu cair pereda masuk angin, permen herbal pelega tenggorokan, suplemen kesehatan daya tahan tubuh.',
    statusPendaftaran: 'Terdaftar',
  },
  {
    nomorPendaftaran: 'IDM000881920',
    nomorPermohonan: 'DID2020081920',
    namaMerek: 'ANTI ANGIN',
    pemilik: 'PT HERBA NUSANTARA SEHAT (Solo, Indonesia)',
    tanggalPenerimaan: '19 Oktober 2020',
    tanggalPerlindungan: '19 Oktober 2030',
    kelasNice: [5],
    uraianBarangJasa: 'Sediaan farmasi herbal, sirup herbal pereda mual dan kembung, kapsul ekstrak jahe dan madu.',
    statusPendaftaran: 'Terdaftar',
  },
  {
    nomorPendaftaran: 'IDM000730192',
    nomorPermohonan: 'DID2018071928',
    namaMerek: 'GR8 TASTE',
    pemilik: 'UNIVERSAL ROBINA CORPORATION (Pasig City, Filipina)',
    tanggalPenerimaan: '30 Juli 2018',
    tanggalPerlindungan: '30 Juli 2028',
    kelasNice: [30],
    uraianBarangJasa: 'Kopi instan 3-in-1, biji kopi, krimer nabati, teh celup wangi melati, biskuit kraker.',
    statusPendaftaran: 'Terdaftar',
  },
  {
    nomorPendaftaran: 'IDM000642190',
    nomorPermohonan: 'DID2017049182',
    namaMerek: 'GREAT TASTE',
    pemilik: 'PT CITRA RASA UTAMA (Surabaya, Indonesia)',
    tanggalPenerimaan: '11 Mei 2017',
    tanggalPerlindungan: '11 Mei 2027',
    kelasNice: [30],
    uraianBarangJasa: 'Serbuk minuman kopi instan, minuman cokelat panas kemasan saset, roti tawar dan roti manis.',
    statusPendaftaran: 'Terdaftar',
  },
  {
    nomorPendaftaran: 'IDM000918293',
    nomorPermohonan: 'DID2021028192',
    namaMerek: 'NITE & DAY',
    pemilik: 'PT METROPOLITAN GOLDEN MANAGEMENT (Jakarta, Indonesia)',
    tanggalPenerimaan: '17 Februari 2021',
    tanggalPerlindungan: '17 Februari 2031',
    kelasNice: [43],
    uraianBarangJasa: 'Jasa perhotelan, penyediaan akomodasi sementara, jasa reservasi hotel dan penginapan, restoran dan kafetaria penyedia makanan dan minuman.',
    statusPendaftaran: 'Terdaftar',
  },
  {
    nomorPendaftaran: 'IDM000754192',
    nomorPermohonan: 'DID2019021948',
    namaMerek: 'NIGHT AND DAY',
    pemilik: 'PT LESTARI INDAH PERHOTELAN (Bali, Indonesia)',
    tanggalPenerimaan: '08 April 2019',
    tanggalPerlindungan: '08 April 2029',
    kelasNice: [43],
    uraianBarangJasa: 'Jasa pelayanan hotel butik, penyediaan fasilitas ruang pertemuan dan perjamuan, kafe kopi.',
    statusPendaftaran: 'Terdaftar',
  },
  {
    nomorPendaftaran: 'IDM000592819',
    nomorPermohonan: 'DID2016041928',
    namaMerek: 'XPRESS COURIER',
    pemilik: 'PT NUSANTARA JASA LOGISTIK (Jakarta, Indonesia)',
    tanggalPenerimaan: '29 Agustus 2016',
    tanggalPerlindungan: '29 Agustus 2026',
    kelasNice: [39],
    uraianBarangJasa: 'Jasa kurir pengiriman dokumen dan barang kilat, jasa pengangkutan kargo darat dan udara, pergudangan barang.',
    statusPendaftaran: 'Terdaftar',
  },
  {
    nomorPendaftaran: 'IDM000710291',
    nomorPermohonan: 'DID2018051928',
    namaMerek: 'EXPRESS LOGISTIK',
    pemilik: 'PT KILAT SEJAHTERA EKSPRES (Surabaya, Indonesia)',
    tanggalPenerimaan: '14 Juni 2018',
    tanggalPerlindungan: '14 Juni 2028',
    kelasNice: [39],
    uraianBarangJasa: 'Jasa kurir pos kilat khusus, layanan ekspedisi muatan paket, jasa penanganan dan penyimpanan barang kiriman.',
    statusPendaftaran: 'Terdaftar',
  },
  {
    nomorPendaftaran: 'IDM000862910',
    nomorPermohonan: 'DID2020101928',
    namaMerek: 'X-TREME GEAR',
    pemilik: 'PT PETUALANG ALAM NUSANTARA (Bandung, Indonesia)',
    tanggalPenerimaan: '03 November 2020',
    tanggalPerlindungan: '03 November 2030',
    kelasNice: [25, 18],
    uraianBarangJasa: 'Pakaian luar tahan air, jaket gunung pelindung angin, celana kargo tahan gesek; tas ransel gunung (carrier), tas pinggang pendaki.',
    statusPendaftaran: 'Terdaftar',
  },
  {
    nomorPendaftaran: 'IDM000749102',
    nomorPermohonan: 'DID2019019283',
    namaMerek: 'EXTREME ADVENTURE',
    pemilik: 'PT WAHANA ALAM LIAR (Bogor, Indonesia)',
    tanggalPenerimaan: '21 Januari 2019',
    tanggalPerlindungan: '21 Januari 2029',
    kelasNice: [25],
    uraianBarangJasa: 'Pakaian pendakian, rompi pelindung, sepatu boot penjelajah alam, topi rimba penahan panas terik.',
    statusPendaftaran: 'Terdaftar',
  }
];
